steps:
#Unit Tests and Build and Push Image
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'unit-tests'
    args: ['verify']
    dir: 'application'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args: ['build', '-t', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '.']
    dir: 'application'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args: ['push', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA']

# Integration Tests using deployed applications
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deployToFunc'
    args: ['beta', 'run', 'deploy', 'cloud-run-test-func', '--image=gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '--region=us-central1', '--platform=managed']
    waitFor: ['push']
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'functional-tests'
    args: ['verify', '-Dtest=com.example.helloworld.RunFuncTest']
    dir: 'cucumber-tests'
    waitFor: ['deployToFunc']

# Integration Tests using deployed applications
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deployToInt'
    args: ['beta', 'run', 'deploy', 'cloud-run-test-int', '--image=gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '--region=us-central1', '--platform=managed']
    waitFor: ['push']
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'integration-tests'
    args: ['verify', '-Dtest=com.example.helloworld.RunIntTest']
    dir: 'cucumber-tests'
    waitFor: ['deployToInt']

# Promote Successful Images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'promoteToStable'
    args: ['tag', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA','gcr.io/pipeline-test-270210/cloud-run-test:TEST']